import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:provider/provider.dart';
import 'package:intl/date_symbol_data_local.dart';
import 'package:firebase_core/firebase_core.dart';
// Note: This file is generated by flutterfire configure
// If it's missing, run: flutterfire configure
import 'firebase_options.dart';

import 'state/app_state.dart';
import 'ui/dashboard_screen.dart';
import 'ui/login_screen.dart';
import 'services/notification_service.dart';

import 'services/log_service.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await initializeDateFormatting('vi_VN', null);

  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    await log.init(); // Initialize global error tracking
    await NotificationService().init();
    log.info("App started successfully with logging enabled");
  } catch (e, stack) {
    log.error("Failed to initialize app", e, stack);
  }

  runApp(
    ChangeNotifierProvider(
      create: (_) => AppState(),
      child: const SettlementApp(),
    ),
  );
}

class SettlementApp extends StatelessWidget {
  const SettlementApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Group Debt Settler',
      debugShowCheckedModeBanner: false,

      // Auto locale follows device
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [
        Locale('vi'),
        Locale('en'),
      ],

      // Auto dark/light mode follows system
      themeMode: ThemeMode.system,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF6366F1),
          brightness: Brightness.light,
        ),
        fontFamily: 'Outfit',
      ),
      darkTheme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF818CF8),
          brightness: Brightness.dark,
        ),
        fontFamily: 'Outfit',
      ),

      home: Consumer<AppState>(
        builder: (context, state, _) {
          if (state.isLoading) {
            return const Scaffold(body: Center(child: CircularProgressIndicator()));
          }
          if (!state.isAuthenticated) {
            return const LoginScreen();
          }
          return const DashboardScreen();
        }
      ),
      builder: (context, child) => GestureDetector(
        onTap: () => FocusManager.instance.primaryFocus?.unfocus(),
        child: child,
      ),
    );
  }
}
